### ISSUE TITLE
Ral iniciar pide "sudo", no funciona sin root?

### ISSUE THREAD

**Issue by Mcalle25** [ivam3/embed#1]

**Comment by ivam3** [comment]
En Android con kernel de 64bits requiere Root, sin embargo si tu Android no es root puedes simularlo bajo el comando proot -0 -w ~ $PREFIX/bin/bash

**Comment by Mcalle25** [comment]
Muchas gracias ! Lo haré, disculpe una consulta... Si instaló Kali net
hunter podré usar el script "embed" o habrá otro que cumpla esa función?

**Comment by ivam3** [comment]
Si es nethunter en Termux si bro

**Comment by Mcalle25** [comment]
Ah ya bro dónde puedo encontrar el link para arreglar el argumento x en
metasploit? No lo encuentro en telegram bro

**Comment by ivam3** [comment]
Hola bro buen dia... solo instala java desde mis repositorios , con ello obtendras la opcion "-x" en metasploit para termux
