### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by moxndam** [ivam3/embed#11]
/data/data/com.termux/files/usr/bin/msfconsole
\033[1;31m\n(_>)─➤\033[0m Metasploit isn't in PATH. Install it. Aborting.

**Comment by ivam3** [comment]
Embed tool needs a metasploit framework to work. So install it first, and then install embed tool.

**Comment by ivam3** [comment]
You can automate the metasploit installation with my script IbyC-installer,  get it on https://bit.ly/3tNTgZL

**Comment by moxndam** [comment]
Thanks
