### ISSUE TITLE
Metasploit isn't in PATH

### ISSUE THREAD

**Issue by Adrihfenty** [ivam3/embed#13]
I'm new using termux, how can i fix this? I have metasploit
![20211117_130203](https://user-images.githubusercontent.com/93755045/142236050-3a099e1d-c877-485d-8914-c90448791507.jpg)

**Comment by ivam3** [comment]
Hola bro, embed busca el directorio metasploit-framework en la ruta $PREFIX/opt, por lo tanto si lo tienes instalado en otra ruta no lo va encontrar.

Así que tienes dos opciones ... 1. Elimina msf y reinstalalo con mi instalador llamado IbyC-installer (https://pastebin.com/Qy7NVgZb) o 2. Crea un enlace simbólico de una ruta a otra para que embed lo encuentre ($ ln -s /ruta/de/tu/metasploit  $PREFIX/opt/metasploit-framework)
