### ISSUE TITLE
Cannot install injected app - There was a problem parsing the package

### ISSUE THREAD

**Issue by karpiyon** [ivam3/embed#15]
Hi,
I am trying to inject the meterpreter/reverese_tcp to an app.
1st I tries with msfvenom -p... and had no problem injected the app, however, msfvenom (most probably apktooks) alter the header of the apps AndroidManifest.xml and prevent the apps from requesting for any permissions.
Therefore, before I try to write my own tool I decided to try `embed`.
I am using the same app I used for msfvenom but this time, when I try to install, on android 10, I get "**There was a problem parsing the package**" error adn the app is not installed.

Of course I renamed the output from .apk_injected to .apk.
I verified the the embed setup process has no errors.
I also tried to manually sign the injected apk. but the result was the same.

I believe this is not an app or device issue since, as I mentioned, msfvenom -p... with the same app and same payload is installing the app.

**Comment by ivam3** [comment]
I think it's about signed apk... let me check it

**Comment by karpiyon** [comment]
can you also check, after you fix it, that the new app with the backdoor has all the permissions it added to the mail xml file.
in all the tests I've done so on Android 10, the new injected app is always installed without the permissions. I tried it with thefatrat and with msfvenom.
I did not have a chance to check it with embed since I could not install the app...
Thanks

________________________________

**Comment by karpiyon** [comment]
BTW, I tried signing the apk, as I do with other apks and I got the same result.
It's not that is tells me that the app was not installed, which it does when the app is not signed properly, it reports that "_There was a problem parsing the package_"

**Comment by MARDQI** [comment]
Hola,  tengo el mismo problema. Cuando embed termina de inyectar el payload en la apk y me devuelve el archivo con extensión .apk_final le cambio el nombre y no instala, probé instalarlo con SAI y me da este error
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl666522601.tmp/0.apk: Corrupt XML binary file

**Comment by ivam3** [comment]
Apktool updated at version 2.7.0 with it the corrupted smali and classes in rebuilding process was fixed and the apk files with minSDKversion 23 can be manipulate

**Comment by Tyagiparrot** [comment]
when I am installing application in my android (brand nameone plus Nord CE 2). It is giving me a error: There was a problem parsing the error. 

PLease help me in this solution.

**Comment by XOMO1** [comment]
hi im currently having the same problem could someone tell me how to fix that?
