### ISSUE TITLE
Error WARNING: linker: Warning: unable to normalize ""

### ISSUE THREAD

**Issue by fazelit** [ivam3/embed#2]
Hi. Thanks for your good program. But I get the following warning when running code:

bash: /data/data/com.termux/files/home/.IbyC/embed: No such file or directory
WARNING: linker: Warning: unable to normalize ""

**Comment by ivam3** [comment]
Revisa los permisos del archivo /data/data/com.termux/files/home/.IbyC/embed o bien asignale los permisos de ejecucion con $]> chmod +x /data/data/com.termux/files/home/.IbyC/embed

**Comment by fazelit** [comment]
Tank you but error cannot find
chmod +x /data/data/com.termux/files/home/.IbyC/embed
chmod: cannot access '/data/data/com.termux/files/home/.IbyC/embed': No such file or directory

$ pwd
/data/data/com.termux/files/home
$ ls -a
 .                 data
 ..                embed
 .android          hk.keystore
 .bash_history     java
 .bundle           key.jks
 .cache            metasploit-framework
 .gem              metasploit.sh
 .msf4             pass.txt
 .python_history   postgresql_ctl.sh
 .screen           python
 .ssh              storage
 .termux           unsignhk.apk
 .wget-hsts        vpn.sh
'?'
$

***-*-***-*-*****-**--

$ cd embed/
$ pwd
/data/data/com.termux/files/home/embed
$ ls -a
 .      '?'         Gemfile.lock   setup
 ..      Apks       LICENSE
 .IbyC   EMBED.rb   README.md
 .git    Gemfile    set-apktool
$

**Comment by fazelit** [comment]
Error in apktool app
Does it need a root?

**Comment by ivam3** [comment]
Yep it need it but it your device isnt rooted you can use a fakeroot as proot, example: proot -0 -w ~ $SHELL
