### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by cobayashi7411** [ivam3/embed#38]
![Screenshot_2023-06-25_15-03-39](https://github.com/ivam3/embed/assets/92548569/79f93f49-2d34-464d-85d0-67ca77c6799d)

**Comment by ivam3** [comment]
Ya se ha actualizado la versión de apktool a 2.8.1 la cual permite ma version de sdk 28, revisala, ya que probablemente estés usando un apk con la versión no soportada de apktool en ese entonces
